name: Docker build

on:
  workflow_dispatch:
  push:
    branches:
      - 'test'
    paths:
      - src/**
  pull_request:
    branches:
      - 'test'
    paths:
      - src/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            accountingservice:
              - 'src/accountingservice/**'

      - if: steps.filter.outputs.accountingservice == 'true'
        name: Test
        run: echo "HERE"

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: name/app

      # - name: Prompt Docker tag
      #   run: echo ${{ steps.meta.outputs.tags }}

      # - name: Docker Login
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     file: ./src/accountingservice/Dockerfile
      #     context: .
      #     push: false
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
