name: Docker build

on:
  workflow_dispatch:
  push:
    branches:
      - 'test'
    paths:
      - src/**
  pull_request:
    branches:
      - 'test'
    paths:
      - src/**

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file_tag:
          - file: ./src/adservice/Dockerfile
            tag_suffix: adservice
            context: ./
          - file: ./src/accountingservice/Dockerfile
            tag_suffix: accountingservice
            context: ./
    
    steps:

      # Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Extract the branch name for commit path filtering
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Prompt branch name
        shell: bash
        run: echo "${{ steps.extract_branch.outputs.branch }}"

      # Detect which services have changes
      - name: Detect changes in services
        uses: dorny/paths-filter@v2
        id: detect_changed_services
        with:
          base: ${{ steps.extract_branch.outputs.branch }}
          filters: |
            accountingservice:
              - 'src/accountingservice/**'
            adservice:
              - 'src/adservice/**'

      # Put services with changes into a variable
      - name: Set changes in services
        id: set_changed_services
        shell: bash
        run: |
          services=""
          if [[ ${{ steps.detect_changed_services.outputs.accountingservice }} == 'true' ]]; then
            services="${services}|accountingservice"
          fi
          if [[ ${{ steps.detect_changed_services.outputs.adservice }} == 'true' ]]; then
            services="${services}|adservice"
          fi
          echo "services=${services}" >> $GITHUB_OUTPUT

      - name: Prompt changes in services
        run: echo "${{ steps.set_changed_services.outputs.services }}"

      # - name: Contains adservice
      #   if: contains(steps.set_changed_services.outputs.services, 'adservice')
      #   run: echo "adservice"

      - name: Contains
        if: contains(steps.set_changed_services.outputs.services, matrix.file_tag.tag_suffix)
        run: echo "${{ matrix.file_tag.tag_suffix }}"

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: name/app

      # - name: Prompt Docker tag
      #   run: echo ${{ steps.meta.outputs.tags }}

      # - name: Docker Login
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     file: ./src/accountingservice/Dockerfile
      #     context: .
      #     push: false
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
