name: Docker build

on:
  workflow_dispatch:
  push:
    branches:
      - 'test'
    paths:
      - src/**
  pull_request:
    branches:
      - 'test'
    paths:
      - src/**

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    env:
      accountingservice: "accountingservice"
    
    steps:

      # Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Extract the branch name for commit path filtering
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Prompt branch name
        shell: bash
        run: echo "${{ steps.extract_branch.outputs.branch }}"

      # Add filters for each service
      - name: Detect changes in services
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ steps.extract_branch.outputs.branch }}
          filters: |
            accountingservice:
              - 'src/accountingservice/**'

      - name: Set changes in services
        id: set_changed_services
        shell: bash
        run: |
          services=""
          services="${services}|accountingservice"
          echo $services
          echo "services=${services}" >> $GITHUB_OUTPUT

      - name: Promt changes in services
        shell: bash
        run: |
          echo "${{ steps.set_changed_services.outputs.services }}"

      - name: Contains yes
        if: contains(${{ steps.set_changed_services.outputs.services }}, 'accountingservice')
        run: echo "YES"

      - name: Contains no
        if: contains(${{ steps.set_changed_services.outputs.services }}, 'adservice')
        run: echo "YES"

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: name/app

      # - name: Prompt Docker tag
      #   run: echo ${{ steps.meta.outputs.tags }}

      # - name: Docker Login
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     file: ./src/accountingservice/Dockerfile
      #     context: .
      #     push: false
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
